### ISSUE TITLE
Is there an advantage of using it over another existing implementation?

### ISSUE THREAD

**Issue by ashar6194** [otaheri/MANO#1]
Hi Omad,

Thanks for providing the repo. Quick question-

Does this have any specific advantage over using the Yana Hasson version--
https://github.com/hassony2/manopth ??
Thanks

**Comment by otaheri** [comment]
Hi Ashar,
This implementation is from the official smplx ([https://github.com/vchoutas/smplx](https://github.com/vchoutas/smplx)) package. I have not used the other version, so I can not comment on it :), but you can give both a try and let us know if there is a difference. 
Thanks

**Comment by anilesec** [comment]
@ashar6194  Did you find any differences in both the implementation?
