### ISSUE TITLE
Visualizing coordinate axes with the rendered mesh

### ISSUE THREAD

**Issue by homangab** [otaheri/MANO#10]
Hello! Thanks for this great repo. I was wondering if you could kindly share the script / command for generating something like the teaser figure in your repo https://github.com/otaheri/MANO/blob/master/images/teaser.png ? 

Specifically, I want to visualize the corresponding coordinate axes along with the rendered mesh, so any pointers regarding that would be helpful. Thank you :)

**Comment by otaheri** [comment]
Hi @homangab, I used pyrender to do this. You should create a scene and after adding the meshes to it, then you can visualize the coordinate axis by pushing the "i" key on your keyboard. To make the meshes wireframe, simply hit the "w" key. You can control more other things there. You can take a look at [this](https://github.com/otaheri/GrabNet/blob/master/grabnet/tools/meshviewer.py) script that I used, I hope this helps.
