### ISSUE TITLE
What's the order of the oupt joints?

### ISSUE THREAD

**Issue by MengHao666** [otaheri/MANO#3]
First thanks for such great work!

Does the order of output joints follow the MANO convention?
I don't know the exact order if u use number 1,2,3 to identify.
`JOINT_NAMES = [
    'wrist',
    'index1',
    'index2',
    'index3',
    'middle1',
    'middle2',
    'middle3',
    'pinky1',
    'pinky2',
    'pinky3',
    'ring1',
    'ring2',
    'ring3',
    'thumb1',
    'thumb2',
    'thumb3',    
    'thumb_tip',
    'index_tip',
    'middle_tip',
    'ring_tip',
    'pinky_tip',
]`
Thanks!

**Comment by otaheri** [comment]
Thanks for your interest in our work :). 

The order is exactly based on the JOINT_NAMES list [here](https://github.com/otaheri/MANO/blob/master/mano/joints_info.py). Just notice that you only get the tip joints if you pass the "return_tips=True" when calling the forward function.

**Comment by MengHao666** [comment]
I think I need to get things more clearly. I mean what is oredr by using the number , e.g.  'index1', 'index2', 'index3'.
Is that from palm to tip, or from tip to palm?

**Comment by otaheri** [comment]
yes, 'index1' to 'index3' is from the palm to the tip and it is similar to other fingers.

**Comment by MengHao666** [comment]
Thanks for reply.
And this repo should adapt to left hand as well.
