### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by sujaltv** [otaheri/MANO#4]
Syntax error in [`model.py`](https://github.com/otaheri/MANO/blob/4b3e48e54c273004d1072df360205278293d0ca7/mano/model.py#L215) in the ["resolved the bug to get fingertips"](https://github.com/otaheri/MANO/commit/4b3e48e54c273004d1072df360205278293d0ca7) commit: an extra closing parenthesis.

```bash
SyntaxError: invalid syntax
```

**Comment by otaheri** [comment]
Thanks for reporting the bug, just fixed it.
